# Generated by Django 4.0.3 on 2022-04-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('is_directed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='graph.vertex')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig', to='graph.vertex')),
            ],
        ),
    ]
