# Generated by Django 4.0.3 on 2022-04-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_edge_weight_alter_vertex_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertex',
            name='is_directed',
        ),
    ]
