# Generated by Django 4.0.3 on 2022-04-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_remove_vertex_is_directed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_directed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vertex',
            name='label',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graph.graph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vertex',
            name='graph',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='graph.graph'),
            preserve_default=False,
        ),
    ]
